name: Deploy Backend to Cloud Run

on:
  push:
    branches: [ main ]
    paths:
      - 'echo-backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./echo-backend

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './echo-backend/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Build TypeScript
      run: npm run build

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and push container
      run: |
        gcloud builds submit --tag asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/echo-app/echo-backend:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy echo-backend-api \
          --image asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/echo-app/echo-backend:${{ github.sha }} \
          --platform managed \
          --region asia-northeast1 \
          --allow-unauthenticated \
          --memory 512Mi